include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    curly_braces_in_flow_control_structures: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    sort_child_properties_last: ignore
    use_build_context_synchronously: ignore
